# -*- coding: utf-8 -*-
"""Pertemuan ke-3_batch13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Piuw383Mef75Jsl_n1jrOYxTcomcS8A_

#Pembahasan assignment#1
"""

# Soal 1
nama = input("Nama: ")
umur = int(input("Umur: "))
tinggi = float(input("Tinggi: "))

text = "Nama saya {}, umur saya {} tahun dan tinggi saya {} cm".format(nama, umur, tinggi)

print(text)

# Soal 2

r = float(input("Masukkan jari-jari lingkaran: "))
pi = 22/7

luas = pi * r * r
luas2 = round(luas,2)

print("Luas Lingkaran dengan jari-jari",r,"cm adalah", luas2,"cm\u00b2")
print("Luas Lingkaran dengan jari-jari",r,"cm adalah {:.2f}".format(luas),"cm\u00b2")

# Soal 3

nilai_minimum = float(input("Nilai minimun: "))

nilai_teori = float(input("Nilai teori: "))
nilai_praktek = float(input("Nilai praktek: "))

if nilai_teori >= nilai_minimum and nilai_praktek >= nilai_minimum:
    print("Lulus")
elif nilai_teori >= nilai_minimum and nilai_praktek < nilai_minimum:
    print("Anda mengulang ujian praktek")
elif nilai_teori < nilai_minimum and nilai_praktek >= nilai_minimum:
    print("Anda mengulang ujian teori")
else:
    print("Anda mengulang ujian teori dan praktek")

"""# Range"""

for i in range (3):
  print(i)

for x in range (1,3):
  print(x)

for y in range (2, 20,3):
  print (y)

"""# Break"""

for i in range(6):
  if i == 3:
    break
  print(i)

for i in range(5):
  if i == 3:
    break
    print(i)

for i in range(5):
  if i == 3:
    break
print(i)

"""# Continue"""

for i in range(10):
  if i == 3:
    continue
  print(i)

for i in range(10):
  if i == 3:
    continue
  elif i == 7:
    continue
  print(i)

for i in range(10):
  if i == 3,5:
    continue
  print(i)

"""# List"""

mylist = ['a','b','c','d','e']
print(mylist)

mylist.remove('a')
print(mylist)

mylist2 = ['a','b','c','d','e']

for s in mylist2:
  print(s)

mylist2.remove('c')

for t in mylist2:
  print(t)

"""# Pendalaman Loop

Kita diminta membuat sebuah program untuk menerima memasukkan sejumlah data pelanggan
sejumlah n orang dengan n adalah integer berisi nama dan umur.

Contoh:
    
Berapa data pelanggan: 2

Masukkan data pelanggan

Pelanggan ke 1
Nama : Iqbal
Umur : 21

Pelanggan ke 2
Nama : Aris
Umur : 22

Pelanggan yang terdaftar adalah :

Pelanggan Iqbal berumur 21

Pelanggan Aris berumur 22
"""

count = int(input('Berapa data pelanggan:'))

nama_pelanggan = []
umur_pelanggan = []

for i in range(count):
  print('Pelanggan ke-{}'.format(i+1))
  nama = input('Nama:')
  umur = int(input('Umur'))

  nama_pelanggan.append(nama)
  umur_pelanggan.append(umur)

print('\nPelanggan yang terdaftar adalah:')

for x in range(len(nama_pelanggan)):
  print('Pelanggan {} berumur {}'.format(nama_pelanggan[x], umur_pelanggan[x]))

for x in range(len(nama_pelanggan)):
  print('Pelanggan {} berumur {}'.format(nama_pelanggan, umur_pelanggan))

"""# While"""

i = 1
while i < 6:
  print(i)
  i +=1

"""# While True"""

# Tanpa while True

operasi = input('Silahkan pilih menu= 1:Penjumlahan, 2:Pengurangan, 3:Perkalian, 4:Pembagian, 5:Keluar')

if operasi == '1':
    x = int(input('Masukkan angka ke-1:'))
    y = int(input('Masukkan angka ke-2'))
    print('Nilai {} + {}'.format(x,y),'=',x+y)
    print('==========================')
elif operasi == '2':
    x = int(input('Masukkan angka ke-1:'))
    y = int(input('Masukkan angka ke-2'))
    print('Nilai {} - {}'.format(x,y),'=',x-y)
    print('==========================')
elif operasi == '3':
    x = int(input('Masukkan angka ke-1:'))
    y = int(input('Masukkan angka ke-2'))
    print('Nilai {} x {}'.format(x,y),'=',x*y)
    print('==========================')
elif operasi == '4':
    x = int(input('Masukkan angka ke-1:'))
    y = int(input('Masukkan angka ke-2'))
    print('Nilai {} : {}'.format(x,y),'=',x/y)
    print('==========================')
elif operasi == '5':
    print('\nOke, terima kasih telah menggunakan kalkulator ini')
    print('==========================')
else:
    print('\nMaaf, pilihan menu angka tidak ada')
    print('==========================')

# Dengan while True

while True:

    operasi = input('Silahkan pilih menu= 1:Penjumlahan, 2:Pengurangan, 3:Perkalian, 4:Pembagian, 5:Keluar')

    if operasi == '1':
        x = int(input('Masukkan angka ke-1:'))
        y = int(input('Masukkan angka ke-2'))
        print('Nilai {} + {}'.format(x,y),'=',x+y)
        print('==========================')
    elif operasi == '2':
        x = int(input('Masukkan angka ke-1:'))
        y = int(input('Masukkan angka ke-2'))
        print('Nilai {} - {}'.format(x,y),'=',x-y)
        print('==========================')
    elif operasi == '3':
        x = int(input('Masukkan angka ke-1:'))
        y = int(input('Masukkan angka ke-2'))
        print('Nilai {} x {}'.format(x,y),'=',x*y)
        print('==========================')
    elif operasi == '4':
        x = int(input('Masukkan angka ke-1:'))
        y = int(input('Masukkan angka ke-2'))
        print('Nilai {} : {}'.format(x,y),'=',x/y)
        print('==========================')
    elif operasi == '5':
        print('\nOke, terima kasih telah menggunakan kalkulator ini')
        print('==========================')
        break
    else:
        print('\nMaaf, pilihan menu angka tidak ada')
        print('==========================')

"""# Nested loop"""

for i in range (2):
  for j in range (3):
    print('i:{}, j:{}'.format(i,j))
  print()

for i in range (2):
  for j in range (3):
    print('i:{}, j:{}'.format(i,j))

for i in range (2):
  for j in range (3):
    print()
    print('i:{}, j:{}'.format(i,j))

for i in range (5):
  for j in range (3):
    print('i:{}, j:{}'.format(i,j))
  print()

for i in range (5):
  for j in range (3):
    print('i:{}, j:{}'.format(i,j),end ='')
  print()

for i in range (5):
  for j in range (3):
    print('i:{}'.format(i),end ='')
      print('j:{}'.format(j))
  print()

for i in range (2):
  for j in range (3):
    print('i:{}, j:{}'.format(i,j),end ='')
  print()

for baris in range (2):
  for kolom in range (3):
    print('{}, {}'.format(baris,kolom))
  print()

"""# Exception

Buat program interaktif yang akan mengeluarkan output "Kelipatan 7" apabila input yang dimasukkan adalah merupakan bilangan kelipatan 7, dan "Bukan Kelipatan 7" jika sebaliknya
"""

angka = int(input('Masukkan angka:'))
if angka == 0:
    print('Bukan Kelipatan 7')
elif angka %7 != 0:
    print('Bukan Kelipatan 7')
elif angka %7 == 0:
    print('Kelipatan 7')

try:
    angka = int(input('Masukkan angka:'))
    if angka == 0:
        print('Bukan Kelipatan 7')
    elif angka %7 != 0:
        print('Bukan Kelipatan 7')
    elif angka %7 == 0:
        print('Kelipatan 7')
except:
    print('Data yang diinput bukan angka')

"""# Contoh lain exception

Buatlah program interaktif untuk mengecek inputan user dengan ketentuan sebagai berikut:
1.program akan menampilkan 'Input tidak Valid' jika yang dimasukkan bukan angka;
2.program akan menampilkan 'Input Diluar Range' jika angka yang dimasukkan tidak diantara 0-99;
3.program akan menampilkan 'Input Valid' jika input berupa angka dan ada di antara 0-99
"""

while True:
    awalan = input('\nSilahkan pilih menu= 1:Menjalankan program, 2:Keluar program\n')
    
    if awalan == '1':
        try:
            angka = int(input('Masukkan angka:'))
            if angka < 0 or angka > 99:
                print('Input diluar range')
            elif angka >= 0 and angka <=99:
                print('Input valid')
        except:
            print('Input tidak valid')
    elif awalan == '2':
        print('\nOke, terima kasih telah menggunakan program ini')
        print('==========================')
        break

while True:
    operasi = input('Silahkan pilih menu= 1:Penjumlahan, 2:Pengurangan, 3:Perkalian, 4:Pembagian, 5:Keluar')

    if operasi == '1':
        try:
            x = int(input('Masukkan angka ke-1:'))
            y = int(input('Masukkan angka ke-2'))
            print('Nilai {} + {}'.format(x,y),'=',x+y)
            print('==========================')
        except:
            print('Input tidak valid')
            print('==========================')
    elif operasi == '2':
        try:
            x = int(input('Masukkan angka ke-1:'))
            y = int(input('Masukkan angka ke-2'))
            print('Nilai {} - {}'.format(x,y),'=',x-y)
            print('==========================')
        except:
            print('Input tidak valid')
            print('==========================') 
    elif operasi == '3':
        try:
            x = int(input('Masukkan angka ke-1:'))
            y = int(input('Masukkan angka ke-2'))
            print('Nilai {} x {}'.format(x,y),'=',x*y)
            print('==========================')
        except:
            print('Input tidak valid')
            print('==========================') 
    elif operasi == '4':
        try:
            x = int(input('Masukkan angka ke-1:'))
            y = int(input('Masukkan angka ke-2'))
            print('Nilai {} : {}'.format(x,y),'=',x/y)
            print('==========================')
        except:
            print('Input tidak valid')
            print('==========================') 
    elif operasi == '5':
        print('\nOke, terima kasih telah menggunakan kalkulator ini')
        print('==========================')
        break
    else:
        print('\nMaaf, pilihan menu angka tidak ada')
        print('==========================')

